spring:
  datasource:
    url: "jdbc:h2:mem:test"
    username: username
    password: pw
    driver-class-name: org.h2.Driver
  #  driver-class-name: com.mysql.cj.jdbc.Driver
  #  url: "jdbc:mysql://localhost:3306/"
  #  username: "cammeet"
  #  password: "cammeet"

  jpa:
    #    database: mysql
    #    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

    show-sql: true
  #
  #  redis:
  #    port: 6379
  #    host: redis
  #
  redis:
    port: 6379
    host: localhost

  mail:
    host: smtp.gmail.com
    port: 587
    username: campusmeet123@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  secret: "FhlUydg3RUhIWphN5SzGr5o6oF2T9JazpFwSi23vDFs="
